# Generated by Django 5.2.3 on 2025-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_clinicsignin_distributorsignin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_license', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DistributorSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distributor_license', models.CharField(max_length=100, unique=True)),
                ('subsection', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='clinicsignin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='distributorsignin',
            name='email',
        ),
        migrations.AddField(
            model_name='clinicsignin',
            name='clinic_license',
            field=models.CharField(default='permanent_license', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='distributorsignin',
            name='distributor_license',
            field=models.CharField(default='permanent_license', max_length=100, unique=True),
        ),
    ]
