# Generated by Django 5.2.3 on 2025-06-25 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0006_user_clinicprofile_distributorprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_clinic_license', message='Clinic license must start with C followed by 4-14 alphanumeric characters', regex='^C[A-Z0-9]{4,14}$')])),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_distributor_license', message='Distributor license must start with D followed by 4-14 alphanumeric characters', regex='^D[A-Z0-9]{4,14}$')])),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='distributorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='ClinicProfile',
        ),
        migrations.DeleteModel(
            name='DistributorProfile',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
