# Generated by Django 5.2.3 on 2025-06-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0007_clinic_distributor_remove_distributorprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='name',
            field=models.CharField(default='Clinic Name', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='subsector',
            field=models.CharField(choices=[('Pharmaceutical', 'Pharmaceutical'), ('Medical Equipment', 'Medical Equipment'), ('Laboratory Supplies', 'Laboratory Supplies'), ('Other', 'Other')], default='Subsector Type', max_length=100),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='license_number',
            field=models.CharField(default='C0000000', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='license_number',
            field=models.CharField(default='D0000000', max_length=15, unique=True),
        ),
    ]
